<<<<<<< HEAD
# Generated by Django 4.2.7 on 2024-02-08 05:30
=======
# Generated by Django 5.0 on 2024-02-07 15:09
>>>>>>> 1ea2990fd88a65e24530d9b0d4d112200fce3e1e

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Subadmin', 'Subadmin'), ('Staff', 'Staff')], max_length=20)),
            ],
        ),
    ]
