# Generated by Django 4.2.7 on 2024-01-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient_or_admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(blank=True, max_length=500, null=True, unique=True)),
            ],
        ),
    ]
