# Generated by Django 5.0 on 2024-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_or_admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(blank=True, max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
