# Generated by Django 4.2.7 on 2024-02-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_remove_userrole_description_alter_userrole_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRUDPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
