# Generated by Django 5.0 on 2024-02-20 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_crudpermission_menupermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crudpermission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='crudpermission',
            name='name',
        ),
        migrations.AddField(
            model_name='crudpermission',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crudpermission',
            name='edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crudpermission',
            name='insert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crudpermission',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='role.userrole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crudpermission',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crudpermission',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
