# Generated by Django 5.0 on 2024-02-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0005_remove_crudpermission_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crudpermission',
            name='verification_status',
        ),
    ]
