# Generated by Django 5.0 on 2024-02-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0006_remove_crudpermission_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudpermission',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
