# Generated by Django 5.0 on 2024-02-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_register',
            name='identy_no',
        ),
    ]
