# Generated by Django 5.0 on 2024-03-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_user_register_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
