# Generated by Django 5.0 on 2024-03-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_user_register_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_register',
            name='user_image',
        ),
    ]
