# Generated by Django 4.2.7 on 2023-12-06 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dashboard_from", "0010_rename_nam_sub_disease_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="department_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, max_length=100, null=True)),
                ("put", models.CharField(max_length=50)),
                (
                    "select_dep",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard_from.doctor_depert_name",
                    ),
                ),
            ],
        ),
    ]
