# Generated by Django 5.0 on 2023-12-21 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '__first__'),
        ('divisions', '__first__'),
        ('hospital_categories', '__first__'),
        ('stations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='hospital_images/')),
                ('description', models.TextField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districts.district')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.division')),
                ('hos_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_categories.hospitalcategory')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
        ),
    ]
