# Generated by Django 4.2.3 on 2023-12-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('disease', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom1', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom2', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom3', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom4', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom5', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom6', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom7', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom8', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom9', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom10', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom11', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom12', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom13', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom14', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom15', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom16', models.CharField(blank=True, max_length=255, null=True)),
                ('symptom17', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.diseases')),
            ],
        ),
    ]
