# Generated by Django 4.2.7 on 2023-12-15 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('confirm_password', models.CharField(max_length=255)),
                ('nid_or_birth_certificate', models.CharField(max_length=255)),
                ('v_code', models.CharField(max_length=500, unique=True)),
                ('v_status', models.CharField(max_length=100)),
            ],
        ),
    ]
