# Generated by Django 4.2.3 on 2023-12-28 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
        ('stations', '0001_initial'),
        ('hospital_categories', '0001_initial'),
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='address_name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hos_name', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='productimg')),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('district_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='districts.district')),
                ('division_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='divisions.division')),
                ('hos_type_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_categories.hospitalcategory')),
                ('station_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
        ),
    ]
