# Generated by Django 4.2.7 on 2023-12-06 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dashboard_from", "0010_rename_nam_sub_disease_name"),
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="hospital_department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "select_depart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard_from.doctor_depert_name",
                    ),
                ),
                (
                    "select_hosp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.hospital_categories",
                    ),
                ),
            ],
        ),
    ]
