# Generated by Django 5.0 on 2024-01-21 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0001_initial'),
        ('role', '0002_patient_or_admin_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_role_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.patient_or_admin')),
                ('select_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_user.user_register')),
            ],
        ),
    ]
