# Generated by Django 5.0 on 2024-03-18 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0007_alter_crudpermission_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_url', models.URLField(blank=True, null=True, unique=True)),
                ('menu_icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submenu_name', models.CharField(max_length=200)),
                ('submenu_url', models.URLField(blank=True, null=True, unique=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='menuPermission.menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_permission', models.BooleanField(default=False)),
                ('menus', models.ManyToManyField(related_name='menu_permissions', to='menuPermission.menu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.userrole')),
                ('submenus', models.ManyToManyField(related_name='menu_permissions', to='menuPermission.submenu')),
            ],
        ),
    ]
