# Generated by Django 5.0 on 2024-02-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=100)),
                ('submenu_status', models.BooleanField(default=False)),
                ('menu_url', models.URLField()),
                ('submenu_name', models.CharField(blank=True, max_length=100, null=True)),
                ('submenu_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
