# Generated by Django 5.0 on 2024-02-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_icon',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
