# Generated by Django 5.0 on 2024-02-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0002_menu_menu_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
