# Generated by Django 5.0 on 2024-02-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0003_alter_menu_menu_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='submenu_url',
        ),
        migrations.AddField(
            model_name='menu',
            name='submenu_urls',
            field=models.ManyToManyField(to='menuPermission.submenu'),
        ),
    ]
