# Generated by Django 5.0 on 2024-02-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0004_submenu_remove_menu_submenu_url_menu_submenu_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='submenu_urls',
            field=models.ManyToManyField(related_name='menus', to='menuPermission.submenu'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
