# Generated by Django 5.0 on 2024-02-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0005_alter_menu_submenu_urls_alter_submenu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='submenu_urls',
        ),
        migrations.AddField(
            model_name='menu',
            name='submenu_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Submenu',
        ),
    ]
