# Generated by Django 5.0 on 2024-02-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0008_alter_menu_submenu_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='submenu_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='menu',
            name='submenu_urls',
        ),
        migrations.AddField(
            model_name='menu',
            name='submenu_urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
