# Generated by Django 5.0 on 2024-03-04 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0011_remove_menupermission_can_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupermission',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menuPermission.menu'),
            preserve_default=False,
        ),
    ]
