# Generated by Django 5.0 on 2024-03-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0012_menupermission_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupermission',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menupermission',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menupermission',
            name='can_insert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menupermission',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
    ]
