# Generated by Django 5.0 on 2024-03-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0013_menupermission_can_delete_menupermission_can_edit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupermission',
            name='menu_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
