# Generated by Django 5.0 on 2024-03-04 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0014_menupermission_menu_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menupermission',
            name='menu_url',
        ),
    ]
