# Generated by Django 5.0 on 2024-03-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0018_remove_menupermission_menu_menupermission_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupermission',
            name='submenu',
            field=models.ManyToManyField(related_name='submenu_permissions', to='menuPermission.submenu'),
        ),
    ]
