# Generated by Django 5.0 on 2024-03-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0019_menupermission_submenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='submenu_urls',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
