# Generated by Django 5.0 on 2024-03-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0020_alter_menu_submenu_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_url',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
