# Generated by Django 5.0 on 2024-03-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0021_alter_menu_menu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupermission',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
