# Generated by Django 5.0 on 2024-03-07 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0022_menupermission_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='menuPermission.menu'),
            preserve_default=False,
        ),
    ]
