# Generated by Django 5.0 on 2024-03-10 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0023_submenu_menu'),
        ('role', '0007_alter_crudpermission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupermission',
            name='submenu',
            field=models.ManyToManyField(related_name='menu_permissions', to='menuPermission.submenu'),
        ),
        migrations.CreateModel(
            name='SubmenuPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('view', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.userrole')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu_permissions', to='menuPermission.submenu')),
            ],
        ),
    ]
