# Generated by Django 5.0 on 2024-03-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0024_alter_menupermission_submenu_submenupermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupermission',
            name='submenu',
            field=models.ManyToManyField(related_name='submenu_permissions', to='menuPermission.submenu'),
        ),
        migrations.DeleteModel(
            name='SubmenuPermission',
        ),
    ]
