# Generated by Django 5.0 on 2024-03-10 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0025_alter_menupermission_submenu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('menu_type', models.CharField(choices=[('menu', 'Menu'), ('submenu', 'Submenu')], max_length=10)),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='menuPermission.menuitem')),
            ],
        ),
    ]
