# Generated by Django 5.0 on 2024-03-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0027_remove_menuitem_parent_menu_menuitem_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
