# Generated by Django 5.0 on 2024-03-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuPermission', '0028_menuitem_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
